inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Rakefile'

Rails:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true
