inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'gemfiles/vendor/**/*'

Rails:
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Style/Encoding:
  Enabled: true

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true
