language: ruby
sudo: false
rvm:
  - jruby-head
  - 2.3.3
  - jruby-9.1.6.0
  - 2.2.6
  - 2.1.9

jdk:
  - oraclejdk8

env:
  - JRUBY_OPTS="--dev --debug"

before_install:
  - gem query -i -n '^bundler$' >/dev/null || gem install --no-doc bundler
  - bundle install

gemfile:
  - gemfiles/Gemfile
#  - gemfiles/rails_4.2.gemfile # Same as root Gemfile
  - gemfiles/rails_4.1.gemfile

matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/Gemfile

script: bundle exec rake test
